server:
  port: 8066

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: promoter
          uri: http://localhost:8095
          predicates:
            - Path=/promoter/**
        - id: promoter-front
          uri: http://localhost:3000
          predicates:
            - Path=/**
  security:
    oauth2:
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: http://localhost:8055/auth/realms/promoter
        registration:
          keycloak-spring-gateway-client:
            provider: my-keycloak-provider
            scope: openid
            client-id: promoter-client
            client-secret: n5wE7BD29zGAAPUvC3HG1OweZ61Io5PM
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

